pipeline {
    agent any
    environment {
        dockerHome = tool 'myDocker'
        mavenHome = tool 'myMaven'
        PATH = "$dockerHome/bin:$mavenHome/bin:$PATH"
    }
    stages {
        stage('Checkout') {
            steps {
                sh 'mvn --version'
                sh 'docker version'
                echo "Build"
                echo "PATH - $PATH"
                echo "BUILD_NUMBER - $env.BUILD_NUMBER"
                echo "BUILD_ID - $env.BUILD_ID"
                echo "JOB_NAME - $env.JOB_NAME"
                echo "BUILD_TAG - $env.BUILD_TAG"
                echo "BUILD_URL - $env.BUILD_URL"
            }
        }
        stage('Compile') {
            steps {
                // Specify the path to pom.xml for the compile phase
                sh "mvn -f API/pom.xml clean compile"
            }
        }
        stage('Test') {
            steps {
                // Specify the path to pom.xml for the test phase
                sh "mvn -f API/pom.xml test"
            }
        }
        stage('Integration Test') {
            steps {
                // Specify the path to pom.xml for the integration test phase
                sh "mvn -f API/pom.xml failsafe:integration-test failsafe:verify"
            }
        }
    }
    post {
        success {
            echo "Success"
        }
        failure {
            echo "Failure"
        }
    }
}
