pipeline {
    agent any
    environment {
        dockerHome = tool 'myDocker'
        // No need for Maven home
        PATH = "$dockerHome/bin:$PATH"
    }
    stages {
        stage('Checkout') {
            steps {
                sh 'docker version'
                echo "Build"
                echo "PATH - $PATH"
                echo "BUILD_NUMBER - $env.BUILD_NUMBER"
                echo "BUILD_ID - $env.BUILD_ID"
                echo "JOB_NAME - $env.JOB_NAME"
                echo "BUILD_TAG - $env.BUILD_TAG"
                echo "BUILD_URL - $env.BUILD_URL"
            }
        }
        stage('Compile') {
            steps {
                // Replace this with MSBuild command for compilation
                sh "msbuild API/server.csproj /t:Build"
            }
        }
        stage('Test') {
            steps {
                // Replace this with MSBuild command for running tests
                sh "msbuild API/server.csproj /t:Test"
            }
        }
        stage('Integration Test') {
            steps {
                // Replace this with MSBuild command for running integration tests
                sh "msbuild API/server.csproj /t:IntegrationTest"
            }
        }
    }
    post {
        success {
            echo "Success"
        }
        failure {
            echo "Failure"
        }
    }
}
